; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; 共通ライブラリはenvで設定
[env] 
lib_deps =
    hideakitai/TaskManager@^0.5.2
    hideakitai/MsgPacketizer@^0.5.3

; ランチコントローラーの環境設定
[env:Launch]
platform = atmelavr
board = ATmega2560
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit INA219@^1.2.3
	labfruits/Mcp320x@^1.4.2
	hideakitai/TaskManager@^0.5.2
	hideakitai/CRCx@^0.4.0
	hideakitai/MsgPack@^0.4.2
	hideakitai/MsgPacketizer@^0.5.3
build_src_filter = +<LaunchController/LaunchController.cpp>
build_flags = 
    ; (MsgPacketizerの設定)
    -D PACKETIZER_MAX_CALLBACK_QUEUE_SIZE=12 ; subscribe数を8に増やす
    -D MSGPACK_MAX_ARRAY_SIZE=12 ; 配列要素数を12に増やす

    ; (TaskManagerの設定)
    -D ARX_VECTOR_DEFAULT_SIZE=20      ; メインタスク数の上限を20に増やす
    -D TASKMANAGER_MAX_SUBTASKS=8      ; サブタスク数の上限を8に増やす

; サテライトコントローラーの環境設定
[env:Satellite]
platform = atmelavr
board = ATmega2560
framework = arduino
monitor_speed = 115200
upload_protocol = arduinoisp
lib_deps = 
	adafruit/Adafruit INA219@^1.2.3
	labfruits/Mcp320x@^1.4.2
	hideakitai/TaskManager@^0.5.2
	hideakitai/CRCx@^0.4.0
	hideakitai/MsgPack@^0.4.2
    hideakitai/MsgPacketizer@^0.5.3
build_src_filter = +<SatelliteController/SatelliteController.cpp>
build_flags = 
    ; (MsgPacketizerの設定)
    -D PACKETIZER_MAX_CALLBACK_QUEUE_SIZE=12 ; subscribe数を6に増やす
    ; -D MSGPACK_MAX_ARRAY_SIZE=10 ; 配列要素数を10に増やす

    ; (TaskManagerの設定)
    -D ARX_VECTOR_DEFAULT_SIZE=20      ; メインタスク数の上限を20に増やす
    -D TASKMANAGER_MAX_SUBTASKS=8      ; サブタスク数の上限を8に増やす

upload_speed = 19200
upload_flags =
    -C
    ; use "tool-avrdude-megaavr" for the atmelmegaavr platform
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    $BOARD_MCU
    -P
    $UPLOAD_PORT
    -b
    $UPLOAD_SPEED
    -c
    stk500v1
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

; USBポートからの書き込みが不可能なため Arduino ISP を使った書き込みをしている．

; ランチコントローラー2.0の環境設定
[env:Launch2]
platform = atmelavr
board = ATmega2560
framework = arduino
monitor_speed = 115200
lib_deps = 
    ${env.lib_deps}
	adafruit/Adafruit INA219@^1.2.3
	labfruits/Mcp320x@^1.4.2

build_src_filter = +<LaunchController2.0/LaunchController2.0.cpp>
build_flags = 
    ; (MsgPacketizerの設定)
    -D PACKETIZER_MAX_CALLBACK_QUEUE_SIZE=12 ; subscribe数を6に増やす
    ; -D MSGPACK_MAX_ARRAY_SIZE=10 ; 配列要素数を10に増やす

    ; (TaskManagerの設定)
    -D ARX_VECTOR_DEFAULT_SIZE=25      ; メインタスク数の上限を20に増やす
    -D TASKMANAGER_MAX_SUBTASKS=8      ; サブタスク数の上限を8に増やす

; サテライトコントローラー2.0の環境設定
[env:Satellite2]
platform = atmelavr
board = ATmega2560
framework = arduino
monitor_speed = 115200
lib_deps = 
    ${env.lib_deps}
	adafruit/Adafruit INA219@^1.2.3
	labfruits/Mcp320x@^1.4.2
    adafruit/Adafruit ADS1X15 @ ^2.6.2

build_src_filter = +<SatelliteController2.0/SatelliteController2.0.cpp>
build_flags = 
    ; (MsgPacketizerの設定)
    -D PACKETIZER_MAX_CALLBACK_QUEUE_SIZE=12 ; subscribe数を6に増やす
    ; -D MSGPACK_MAX_ARRAY_SIZE=10 ; 配列要素数を10に増やす

    ; (TaskManagerの設定)
    -D ARX_VECTOR_DEFAULT_SIZE=25      ; メインタスク数の上限を20に増やす
    -D TASKMANAGER_MAX_SUBTASKS=8      ; サブタスク数の上限を8に増やす


; ランチコントローラー3.0の環境設定 (Raspberry Pi 4 無線遠隔制御対応)
[env:Launch3]
platform = atmelavr
board = ATmega2560
framework = arduino
monitor_speed = 115200
lib_deps = 
    ${env.lib_deps}
	adafruit/Adafruit INA219@^1.2.3
	labfruits/Mcp320x@^1.4.2

build_src_filter = +<LaunchController3.0/LaunchController3.0.cpp>
build_flags = 
    ; (MsgPacketizerの設定)
    -D PACKETIZER_MAX_CALLBACK_QUEUE_SIZE=12 ; 無線パケット追加に伴いキューサイズを12に拡張
    -D MSGPACK_MAX_ARRAY_SIZE=12

    ; (TaskManagerの設定)
    -D ARX_VECTOR_DEFAULT_SIZE=30      ; メインタスク数の上限を30に拡張
    -D TASKMANAGER_MAX_SUBTASKS=10     ; サブタスク数の上限を10に拡張

; サテライトコントローラー3.0の環境設定 (Raspberry Pi 4 無線遠隔制御対応)
[env:Satellite3]
platform = atmelavr
board = ATmega2560
framework = arduino
monitor_speed = 115200
lib_deps = 
    ${env.lib_deps}
	adafruit/Adafruit INA219@^1.2.3
	labfruits/Mcp320x@^1.4.2
    adafruit/Adafruit ADS1X15 @ ^2.6.2

build_src_filter = +<SatelliteController3.0/SatelliteController3.0.cpp>
build_flags = 
    ; (MsgPacketizerの設定)
    -D PACKETIZER_MAX_CALLBACK_QUEUE_SIZE=12 ; 無線パケット追加に伴いキューサイズを12に拡張
    ; -D MSGPACK_MAX_ARRAY_SIZE=10

    ; (TaskManagerの設定)
    -D ARX_VECTOR_DEFAULT_SIZE=30      ; メインタスク数の上限を30に拡張
    -D TASKMANAGER_MAX_SUBTASKS=10     ; サブタスク数の上限を10に拡張


[env:SatelliteNode]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-ra4m1
framework = arduino

; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; framework = arduino
; board = seeed_xiao_esp32c6
lib_deps = 
    ${env.lib_deps}
    adafruit/Adafruit NeoPixel@^1.13.0
build_src_filter = +<SatelliteNode/SatelliteNode.cpp>
build_flags =
    ; (MsgPacketizerの設定)
    -D PACKETIZER_MAX_CALLBACK_QUEUE_SIZE=12 ; subscribe数を6に増やす
    -D MSGPACK_MAX_ARRAY_SIZE=10 ; 配列要素数を10に増やす

    ; (TaskManagerの設定)
    -D ARX_VECTOR_DEFAULT_SIZE=10      ; メインタスク数の上限を10に増やす
    -D TASKMANAGER_MAX_SUBTASKS=8      ; サブタスク数の上限を8に増やす


; [env:THRValveControlModule]
; platform = https://github.com/Seeed-Studio/platform-seeedboards.git
; board = seeed-xiao-ra4m1
; framework = arduino
; build_src_filter = +<THRValveControlModule/main.cpp>
; lib_deps = 
;     SPI
;     I2C
;     hideakitai/TaskManager@^0.5.2
;     hideakitai/MsgPacketizer@^0.5.3
;     adafruit/Adafruit NeoPixel@^1.13.0

; [env:LogDumper_THRValveControlModule]
; platform = https://github.com/Seeed-Studio/platform-seeedboards.git
; board = seeed-xiao-ra4m1
; framework = arduino
; build_src_filter = +<THRValveControlModule/LogDumper/main.cpp>
; lib_deps = 
;     SPI
;     I2C
;     hideakitai/TaskManager@^0.5.2
;     hideakitai/MsgPacketizer@^0.5.3
;     adafruit/Adafruit NeoPixel@^1.13.0


; [env:ADM2582E_main]
; platform = ststm32
; board = nucleo_f756zg
; framework = arduino
; upload_protocol = stlink
; build_src_filter = +<ADM2582E/main.cpp>
; ; build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
; lib_deps = 
; 	hideakitai/TaskManager@^0.5.2
;  	hideakitai/MsgPacketizer @ ^0.5.3


; [env:ADM2582E_sub]
; platform = ststm32
; board = nucleo_f756zg
; framework = arduino
; upload_protocol = stlink
; build_src_filter = +<ADM2582E/sub.cpp>
; ; build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
; lib_deps = 
; 	hideakitai/TaskManager@^0.5.2
;  	hideakitai/MsgPacketizer @ ^0.5.3

; [env:ADM2582E_sub1]
; platform = ststm32
; board = nucleo_f446re
; framework = arduino
; upload_protocol = stlink
; build_src_filter = +<ADM2582E/sub1.cpp>
; lib_deps = 
; 	hideakitai/TaskManager@^0.5.2
;  	hideakitai/MsgPacketizer @ ^0.5.3

; [env:seeed_xiao_nrf52840_sense]
; platform = https://github.com/Seeed-Studio/platform-seeedboards.git
; board = seeed-xiao-afruitnrf52-nrf52840-sense
; framework = arduino
; monitor_speed = 921600
; lib_archive = no
; lib_deps =
;     https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git
;     hideakitai/TaskManager@^0.5.2
;     hideakitai/MsgPacketizer@^0.5.3

; build_flags = -I include

; build_src_filter = +<XiaoNrf52840/main.cpp>


