M48
; DRILL file {KiCad 7.0.1} date Mon Sep 18 22:16:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-18T22:16:33+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1772
%
G90
G05
T1
X-7.5748Y0.9008
X-7.378Y0.9008
T2
X-7.9807Y0.087
X-7.9807Y-0.363
T3
X0.3937Y-0.3937
X0.3937Y-3.5433
X5.5118Y-0.3937
X5.5118Y-3.5433
T0
M30
